class CfgPatches
{
	class VSM_OGA_Config
	{
		units[]=
		{
			"VSM_OGA_Mod"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F"
		};
	};
};
class cfgFactionClasses
{
	class VSM_GP
	{
		displayName="VSM - Gear Pack";
		priority=1;
		side=1;
		icon="VSM_OGA\Data\moh_icon.paa";
	};
};
class UniformSlotInfo
{
	slotType=0;
	linkProxy="-";
};
class CfgVehicles
{
	class B_Soldier_F;
	class B_Soldier_03_f;
	class B_Soldier_base_F;
	class VSM_OGA_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_OGA_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_OGA_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_OGA_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_od_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_od_pants_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (OD Pants SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_OGA_od_pants_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_od_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_od_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (OD)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_OGA_od_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_od_1_co.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_od_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (OD SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_OGA_od_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_od_1_co.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_od_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (OD - Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_OGA_od_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_od_tan_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_od_tan_pants_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (OD - Tan Pants SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_OGA_od_tan_pants_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_od_tan_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_od_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_od_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_od_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye OD)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_od_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_OD_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_od_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS OD)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_od_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_OD_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_od_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye OD - Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_OD_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_od_tan_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_od_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS OD - Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_OD_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_od_tan_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_od_grey_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye OD - Grey Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_OD_grey_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_od_grey_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_od_grey_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS OD - Grey Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_OD_grey_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_od_grey_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_grey_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye - Grey Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_grey_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_grey_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS - Grey Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_grey_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_grey_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye Grey - OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_grey_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_od_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_grey_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey - OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_grey_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_od_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_grey_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye Grey - Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_grey_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_tan_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_grey_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey - Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_grey_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_tan_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_grey_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye Grey)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_OGA_Crye_grey_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_Crye_SS_grey_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_OGA_Crye_ss_grey_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_ARD_OGA_grey_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_OGA_OD_Casual_uniform: B_Soldier_03_f
	{
		author="VanSchmoozin";
		_generalMacro="B_Soldier_03_f";
		scope=2;
		displayName="[VSM] OGA (OD Button Up) ";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_EPB\Guerrilla\ig_guerrilla5_1.p3d";
		uniformClass="VSM_OGA_OD_Casual_camo";
		modelSides[]={3,1};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsMaterials[]=
		{
			"",
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_black_button_up.paa",
			"VSM_OGA\Data\VSM_ARD_OGA_od_1.paa"
		};
		weapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
	};
	class VSM_OGA_tan_Casual_uniform: B_Soldier_03_f
	{
		author="VanSchmoozin";
		_generalMacro="B_Soldier_03_f";
		scope=2;
		displayName="[VSM] OGA (Tan Button Up) ";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_EPB\Guerrilla\ig_guerrilla5_1.p3d";
		uniformClass="VSM_OGA_tan_Casual_camo";
		modelSides[]={3,1};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsMaterials[]=
		{
			"",
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_black_button_up.paa",
			"VSM_OGA\Data\VSM_ARD_OGA_1.paa"
		};
		weapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
	};
	class VSM_OGA_grey_Casual_uniform: B_Soldier_03_f
	{
		author="VanSchmoozin";
		_generalMacro="B_Soldier_03_f";
		scope=2;
		displayName="[VSM] OGA (Grey Button Up) ";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_EPB\Guerrilla\ig_guerrilla5_1.p3d";
		uniformClass="VSM_OGA_tan_Casual_camo";
		modelSides[]={3,1};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsMaterials[]=
		{
			"",
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_black_button_up.paa",
			"VSM_OGA\Data\VSM_ARD_OGA_grey_1.paa"
		};
		weapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
	};
	class B_AssaultPack_Base;
	class VSM_OGA_Backpack_Compact: B_AssaultPack_Base
	{
		scope=2;
		displayName="[VSM] OGA Compact Bag";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_compact.paa"
		};
	};
	class VSM_OGA_OD_Backpack_Compact: B_AssaultPack_Base
	{
		scope=2;
		displayName="[VSM] OGA Compact Bag [OD] ";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_compact.paa"
		};
	};
	class B_kitbag_Base;
	class VSM_OGA_Backpack_Kitbag: B_kitbag_Base
	{
		scope=2;
		displayName="[VSM] OGA Kitbag";
		author="VanSchmoozin";
		model="A3\weapons_f\ammoboxes\bags\Backpack_fast.p3d";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_kitbag.paa"
		};
	};
	class VSM_OGA_OD_Backpack_Kitbag: B_kitbag_Base
	{
		scope=2;
		displayName="[VSM] OGA Kitbag [OD]";
		author="VanSchmoozin";
		model="A3\weapons_f\ammoboxes\bags\Backpack_fast.p3d";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_kitbag.paa"
		};
	};
	class B_Carryall_Base;
	class VSM_OGA_carryall: B_Carryall_Base
	{
		scope=2;
		displayName="[VSM] OGA CarryAll";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_carryall.paa"
		};
	};
	class VSM_OGA_OD_carryall: B_Carryall_Base
	{
		scope=2;
		displayName="[VSM] OGA CarryAll (OD)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_carryall.paa"
		};
	};
};
class cfgWeapons
{
	class ItemCore;
	class UniformItem;
	class Uniform_Base: ItemCore
	{
		class ItemInfo;
	};
	class VSM_OGA_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Rolled Sleeves)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (OD Pants)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_od_pants_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_od_pants_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (OD Pants Rolled Sleeves)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_od_pants_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_od_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (OD)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_od_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_od_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (OD Rolled Sleeves)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_od_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_od_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (OD - Tan Pants)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_OD_Tan_Pants_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_od_tan_pants_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (OD - Tan Pants Rolled Sleeves)";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_OD_tan_pants_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_OGA_Crye_SS_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye OD Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_od_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS OD Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_OD_Pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_Grey_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye Grey Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_grey_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_grey_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_grey_Pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_od_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye OD)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_od_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_od_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS OD)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_OD_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_od_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye OD - Tan Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_OD_Tan_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_OD_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS OD - Tan Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_OD_Tan_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_od_grey_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye OD - Grey Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_OD_grey_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_OD_grey_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS OD - Grey Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_OD_Grey_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_grey_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye Grey)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_grey_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_grey_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_grey_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_grey_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye Grey - OD Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_grey_Od_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_grey_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey - OD Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_grey_od_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_grey_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye Grey - Tab Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_grey_tan_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_Crye_SS_grey_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye SS Grey - Tan Pants)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_Crye_SS_grey_tan_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_OD_casual_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Crye OD Button Up)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_OD_casual_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_tan_casual_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Tan Button Up)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_tan_casual_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_OGA_grey_casual_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] OGA (Grey Button Up)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_grey.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_OGA_grey_casual_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VestItem;
	class Vest_Camo_Base: ItemCore
	{
		class ItemInfo;
	};
	class VSM_OGA_LBT_vest: Vest_Camo_Base
	{
		scope=2;
		author="VanSchmoozin | Specter";
		displayName="[VSM] OGA LBT 1961a";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="\VSM_Vests\Spectergear_LBT\carrier_rig.p3d";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\VSM_OGA\Data\VSM_OGA_plate.paa",
			"\VSM_OGA\Data\VSM_OGA_chestrig.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\VSM_Vests\Spectergear_LBT\carrier_rig.p3d";
			containerClass="Supply70";
			mass=50;
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"insignia"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_OD_LBT_vest: Vest_Camo_Base
	{
		scope=2;
		author="VanSchmoozin | Specter";
		displayName="[VSM] OGA LBT 1961a [OD]";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="\VSM_Vests\Spectergear_LBT\carrier_rig.p3d";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\VSM_OGA\Data\VSM_OGA_OD_plate.paa",
			"\VSM_OGA\Data\VSM_OGA_OD_chestrig.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\VSM_Vests\Spectergear_LBT\carrier_rig.p3d";
			containerClass="Supply70";
			mass=50;
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"insignia"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_IOTV_1: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA IOTV Lite";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F_beta\indep\equip_ia_vest01.p3d";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_IOTV.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_beta\indep\equip_ia_vest01.p3d";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_IOTV_2: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA IOTV";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F_beta\indep\equip_ia_vest02.p3d";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_IOTV.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_beta\indep\equip_ia_vest02.p3d";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=8;
					passThrough=0.5;
				};
				class Chest
				{
					HitpointName="HitChest";
					armor=30;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=30;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=30;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_OD_IOTV_1: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA IOTV Lite (OD)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F_beta\indep\equip_ia_vest01.p3d";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_IOTV.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_beta\indep\equip_ia_vest01.p3d";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_OD_IOTV_2: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA IOTV (OD)";
		author="VanSchmoozin";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F_beta\indep\equip_ia_vest02.p3d";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_IOTV.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_beta\indep\equip_ia_vest02.p3d";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=8;
					passThrough=0.5;
				};
				class Chest
				{
					HitpointName="HitChest";
					armor=30;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=30;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=30;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_Vest_1: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA Platecarrier";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F\BLUFOR\equip_b_Vest01";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F\BLUFOR\equip_b_Vest01";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_Vest_2: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA Platecarrier Lite";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F\BLUFOR\equip_b_Vest02";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F\BLUFOR\equip_b_Vest02";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=22;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=22;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=22;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_Vest_3: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA Platecarrier Special";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=22;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=22;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=22;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_OD_Vest_1: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA Platecarrier [OD]";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F\BLUFOR\equip_b_Vest01";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F\BLUFOR\equip_b_Vest01";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_OD_Vest_2: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA Platecarrier Lite [OD]";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F\BLUFOR\equip_b_Vest02";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F\BLUFOR\equip_b_Vest02";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=22;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=22;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=22;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_OGA_OD_Vest_3: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] OGA Platecarrier Special [OD]";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=22;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=22;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=22;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class H_HelmetB: ItemCore
	{
		class ItemInfo;
	};
	class VSM_OGA_Helmet1: H_HelmetB
	{
		displayName="[VSM] OGA ECH";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_helmet.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=20;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class VSM_OGA_Helmet2: H_HelmetB
	{
		displayName="[VSM] OGA ECH Lite";
		picture="\VSM_OGA\Data\Icons\VSM_OGA.paa";
		model="A3\Characters_F\BLUFOR\headgear_b_helmet_light";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_helmet.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=15;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\BLUFOR\headgear_b_helmet_light";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class VSM_OGA_OD_Helmet1: H_HelmetB
	{
		displayName="[VSM] OGA ECH [OD]";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_helmet.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=20;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class VSM_OGA_OD_Helmet2: H_HelmetB
	{
		displayName="[VSM] OGA ECH Lite [OD]";
		picture="\VSM_OGA\Data\Icons\VSM_OGA_OD.paa";
		model="A3\Characters_F\BLUFOR\headgear_b_helmet_light";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_OGA\Data\VSM_OGA_OD_helmet.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=15;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\BLUFOR\headgear_b_helmet_light";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
};
class cfgMods
{
	author="76561198040446180";
	timepacked="1471398486";
};
