class CfgPatches
{
	class VSM_MulticamTropic_Config
	{
		units[]=
		{
			"VSM_MulticamTropic_Mod"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F"
		};
	};
};
class cfgFactionClasses
{
	class VSM_GP
	{
		displayName="VSM - Gear Pack";
		priority=1;
		side=1;
		icon="VSM_MulticamTropic\Data\moh_icon.paa";
	};
};
class UniformSlotInfo
{
	slotType=0;
	linkProxy="-";
};
class CfgVehicles
{
	class B_Soldier_F;
	class B_Soldier_03_f;
	class B_Soldier_base_F;
	class VSM_MulticamTropic_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_MulticamTropic_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_od_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_od_pants_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (OD Pants SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_MulticamTropic_od_pants_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_od_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_od_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (OD Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_od_shirt_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_od_shirt_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_od_shirt_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (OD Shirt SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_MulticamTropic_od_shirt_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_od_shirt_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_tan_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_tan_pants_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Pants SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_MulticamTropic_tan_pants_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_tan_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_tan_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_tan_shirt_Camo";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_tan_shirt_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_tan_shirt_Uniform_SS: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Shirt SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass="VSM_MulticamTropic_tan_shirt_Camo_SS";
		hiddenSelections[]=
		{
			"Camo",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_tan_shirt_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_BDU_OD_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (OD Pants BDU)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		uniformClass="VSM_MulticamTropic_BDU_OD_Pants_Camo";
		hiddenSelections[]=
		{
			"Camo1",
			"camo2",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_BDU.paa",
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_od_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_BDU_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (BDU)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		uniformClass="VSM_MulticamTropic_BDU_Camo";
		hiddenSelections[]=
		{
			"Camo1",
			"camo2",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_BDU.paa",
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_BDU_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Pants BDU)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		uniformClass="VSM_MulticamTropic_BDU_Tan_Pants_Camo";
		hiddenSelections[]=
		{
			"Camo1",
			"camo2",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_BDU.paa",
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_tan_pants_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Uniform_TShirt: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Tee)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_f_gamma\Guerrilla\ig_guerrilla1_1.p3d";
		uniformClass="VSM_MulticamTropic_Camo_TShirt";
		hiddenSelections[]=
		{
			"Camo1",
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\MOH_TSHIRT.paa",
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_od_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_od_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS OD Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_od_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_od_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_od_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye OD Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_od_shirt_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_od_shirt_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_od_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS OD Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_od_Shirt_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_od_shirt_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_tan_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_tan_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Tan Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_tan_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_tan_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_tan_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Tan Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_Tan_Shirt_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_tan_shirt_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_tan_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Tan Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_tan_shirt_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_tan_shirt_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_Tee_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Tee)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		uniformClass="VSM_MulticamTropic_Crye_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_grey_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Grey Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_grey_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_grey_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_grey_pants_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Grey Pants)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_grey_pants_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_grey_pants_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_grey_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Grey Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass="VSM_MulticamTropic_Crye_grey_Shirt_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_grey_shirt_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_SS_grey_shirt_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Grey Shirt)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		uniformClass="VSM_MulticamTropic_Crye_ss_grey_shirt_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_grey_shirt_1.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_ProjectHonor\Data\VSM_ARD.RVMAT"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Crye_Thermal_Uniform: B_Soldier_F
	{
		author="VanSchmoozin";
		_generalMacro="B_soldier_F";
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Thermal)";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_Exp\BLUFOR\B_CTRG_Soldier_01_F.p3d";
		uniformClass="VSM_MulticamTropic_Crye_Thermal_Camo";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_Multicam_Tropic_Crye_1_thermal.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class VSM_MulticamTropic_Casual_uniform: B_Soldier_03_f
	{
		author="VanSchmoozin";
		_generalMacro="B_Soldier_03_f";
		scope=2;
		displayName="[VSM] MulticamTropic (Button Up) ";
		identityTypes[]=
		{
			"Head_NATO",
			"G_NATO_default"
		};
		genericNames="NATOMen";
		faction="VSM_GP";
		model="\A3\Characters_F_EPB\Guerrilla\ig_guerrilla5_1.p3d";
		uniformClass="VSM_MulticamTropic_Casual_camo";
		modelSides[]={3,1};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsMaterials[]=
		{
			"",
			"VSM_Projecthonor\Data\VSM_ARD.RVMAT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_Black_button_up.paa",
			"VSM_MulticamTropic\Data\VSM_ARD_MulticamTropic_1.paa"
		};
		weapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
	};
	class B_AssaultPack_Base;
	class VSM_MulticamTropic_Backpack_Compact: B_AssaultPack_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic Compact Bag";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_compact.paa"
		};
	};
	class B_kitbag_Base;
	class VSM_MulticamTropic_Backpack_Kitbag: B_kitbag_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic Kitbag";
		author="VanSchmoozin";
		model="A3\weapons_f\ammoboxes\bags\Backpack_fast.p3d";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_kitbag.paa"
		};
	};
	class B_Carryall_Base;
	class VSM_MulticamTropic_carryall: B_Carryall_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic CarryAll";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_carryall.paa"
		};
	};
};
class cfgWeapons
{
	class ItemCore;
	class UniformItem;
	class Uniform_Base: ItemCore
	{
		class ItemInfo;
	};
	class VSM_MulticamTropic_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Rolled Sleeves)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (OD Pants)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_od_pants_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_od_pants_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (OD Pants Rolled Sleeves)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_od_pants_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_od_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (OD Shirt)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_od_shirt_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_od_shirt_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (OD Shirt Rolled Sleeves)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_od_shirt_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Pants)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Tan_Pants_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_tan_pants_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Pants Rolled Sleeves)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_tan_pants_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_tan_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Shirt)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_tan_shirt_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_tan_shirt_Camo_SS: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Shirt Rolled Sleeves)";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_tan_shirt_Uniform_SS";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_BDU_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (BDU)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_BDU_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_BDU_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (OD Pants BDU)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_BDU_od_pants_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_BDU_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Tan Pants BDU)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_BDU_tan_pants_Uniform";
			containerClass="Supply50";
			mass=50;
		};
	};
	class VSM_MulticamTropic_Camo_TShirt: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (T-Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Uniform_TShirt";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye OD Pants)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_od_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_od_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS OD Pants)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_OD_Pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_od_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye OD Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_od_shirt_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_od_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS OD Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_OD_shirt_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Tan Pants)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_Tan_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_tan_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Tan Pants)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_Tan_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_tan_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Tan Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_tan_shirt_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_tan_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Tan Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_tan_shirt_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_Tee_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Tee)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_Tee_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_grey_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Grey Pants)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_grey_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_grey_pants_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Grey Pants)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_grey_pants_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_grey_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Grey Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_grey_shirt_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_SS_grey_shirt_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye SS Grey Shirt)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_SS_grey_shirt_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_Crye_Thermal_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Crye Thermal)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_Crye_Thermal_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VSM_MulticamTropic_casual_Camo: Uniform_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic (Button Up)";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		class ItemInfo: UniformItem
		{
			uniformClass="VSM_MulticamTropic_casual_Uniform";
			containerClass="Supply30";
			mass=35;
		};
	};
	class VestItem;
	class Vest_Camo_Base: ItemCore
	{
		class ItemInfo;
	};
	class VSM_MulticamTropic_LBT_vest: Vest_Camo_Base
	{
		scope=2;
		author="VanSchmoozin | Specter";
		displayName="[VSM] MulticamTropic LBT 1961a";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="\VSM_Vests\Spectergear_LBT\carrier_rig.p3d";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\VSM_MulticamTropic\Data\VSM_MulticamTropic_plate.paa",
			"\VSM_MulticamTropic\Data\VSM_MulticamTropic_chestrig.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\VSM_Vests\Spectergear_LBT\carrier_rig.p3d";
			containerClass="Supply70";
			mass=50;
			hiddenSelections[]=
			{
				"camo",
				"camo2",
				"insignia"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_MulticamTropic_IOTV_1: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic IOTV Lite";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F_beta\indep\equip_ia_vest01.p3d";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_IOTV.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_beta\indep\equip_ia_vest01.p3d";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_MulticamTropic_IOTV_2: Vest_Camo_Base
	{
		scope=2;
		displayName="[VSM] MulticamTropic IOTV";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F_beta\indep\equip_ia_vest02.p3d";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_IOTV.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_beta\indep\equip_ia_vest02.p3d";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=8;
					passThrough=0.5;
				};
				class Chest
				{
					HitpointName="HitChest";
					armor=30;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=30;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=30;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_MulticamTropic_Vest_1: Vest_Camo_Base
	{
		scope=2;
		author="VanSchmoozin";
		displayName="[VSM] MulticamTropic Platecarrier";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F\BLUFOR\equip_b_Vest01";
		descriptionShort="$STR_A3_SP_AL_IV";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F\BLUFOR\equip_b_Vest01";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=25;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=25;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=25;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_MulticamTropic_Vest_2: Vest_Camo_Base
	{
		scope=2;
		author="VanSchmoozin";
		displayName="[VSM] MulticamTropic Platecarrier Lite";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F\BLUFOR\equip_b_Vest02";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F\BLUFOR\equip_b_Vest02";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=22;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=22;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=22;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_MulticamTropic_Vest_3: Vest_Camo_Base
	{
		scope=2;
		author="VanSchmoozin";
		displayName="[VSM] MulticamTropic Platecarrier Special";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
		descriptionShort="$STR_A3_SP_AL_III";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_Vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="A3\Characters_F_EPA\BLUFOR\equip_b_vest_kerry";
			containerClass="Supply120";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					HitpointName="HitChest";
					armor=22;
					PassThrough=0.30000001;
				};
				class Diaphragm
				{
					HitpointName="HitDiaphragm";
					armor=22;
					PassThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=22;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};
	class VSM_MulticamTropic_Vest_6: Vest_Camo_Base
	{
		author="VanSchmoozin";
		scope=2;
		displayName="[VSM] MulticamTropic Heavy 1";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="\A3\Characters_F\BLUFOR\equip_b_carrier_spec_rig.p3d";
		descriptionShort="$STR_A3_SP_AL_V";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_Heavy.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\A3\Characters_F\BLUFOR\equip_b_carrier_spec_rig.p3d";
			containerClass="Supply100";
			mass=100;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=8;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=8;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.60000002;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.60000002;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.60000002;
				};
			};
		};
	};
	class VSM_MulticamTropic_Vest_7: Vest_Camo_Base
	{
		author="VanSchmoozin";
		scope=2;
		displayName="[VSM] MulticamTropic Heavy 2";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="\A3\Characters_F\BLUFOR\equip_b_carrier_gl_rig.p3d";
		descriptionShort="$STR_A3_SP_AL_V";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_Heavy.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\A3\Characters_F\BLUFOR\equip_b_carrier_gl_rig.p3d";
			containerClass="Supply100";
			mass=100;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=8;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=8;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.60000002;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.60000002;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.60000002;
				};
			};
		};
	};
	class H_HelmetB: ItemCore
	{
		class ItemInfo;
	};
	class VSM_MulticamTropic_Helmet1: H_HelmetB
	{
		displayName="[VSM] MulticamTropic ECH";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_helmet.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=20;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class VSM_MulticamTropic_Helmet2: H_HelmetB
	{
		displayName="[VSM] MulticamTropic ECH Lite";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F\BLUFOR\headgear_b_helmet_light";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_helmet.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=15;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\BLUFOR\headgear_b_helmet_light";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
	class VSM_MulticamTropic_Boonie: H_HelmetB
	{
		displayName="[VSM] MulticamTropic Boonie";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F\Common\booniehat";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_boonie.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=15;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\Common\booniehat";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			passThrough=0.60000002;
		};
	};
	class VSM_MulticamTropic_Cap: H_HelmetB
	{
		displayName="[VSM] MulticamTropic Cap";
		author="VanSchmoozin";
		picture="\VSM_MulticamTropic\Data\Icons\VSM_MulticamTropic.paa";
		model="A3\Characters_F\Common\cappatrol.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_MulticamTropic\Data\VSM_MulticamTropic_cap.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=3;
			allowedSlots[]={901,605};
			uniformModel="A3\Characters_F\Common\cappatrol.p3d";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo"
			};
			passThrough=0.60000002;
		};
	};
};
class cfgMods
{
	author="76561198040446180";
	timepacked="1471398460";
};
